### ISSUE TITLE
Incomplete build instructions: 'gitToken' not defined in local.properties

### ISSUE THREAD

**Issue by MihaiB** [ProtonMail/proton-mail-android#38]
A clean build of the project in Android Studio gives this error:
```
'gitToken' not defined in local.properties. 
Define it locally as 'gitToken=MY_ACCESS_TOKEN' and on CI as environment variable named 'GIT_TOKEN' 
```

Setting literally `gitToken=MY_ACCESS_TOKEN` in `local.properties` seems to solve the issue, but since that file is only created on the first (failed) build, what is the proper way to solve this?
(Adding a manual step to the README "build with Android Studio, get the error, set gitToken and rebuild" feels like a workaround.)

**Comment by 4face-studi0** [comment]
Thank you for the report.
`gitToken` is our personal GitLab token, required to fetch Detekt ruleset from the Core Project on GitLab.
Since Core got a different workflow which allow us to sync to GitHub at each merge into `develop`, we're working to switch the fetching from the [GitHub Repository](https://github.com/ProtonMail/protoncore_android)
